server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/VladislavDemchenko/project-configs.git
          default-label: master
#            search-paths: '{application}'